# -*- coding: utf-8 -*-
"""tutorial2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VnBzxpIAwe1oF4oMFiE-lnLfHcjYwdBU

# Eso es un tutorial
Importar Librerias
"""

import folium
import pandas as pd

map = folium.Map (location=[20 , 0], zoom_start=8)
map

map = folium.Map(location=[-2.0101, -78.848], zoom_start=8)
map

info_montana = pd.read_csv('mountain_ecuador.csv')
info_montana

map = folium.Map(location=[-2.0101, -78.848], zoom_start=8, tiles = 'Stamen Terrain')
for i in range (0, len(info_montana)):

  Nombre = info_montana.iloc[i]['Montaña']
  Latitud =  info_montana.iloc[i]['Latitud']
  Longitud =  info_montana.iloc[i]['Longitud']
  Elevacion = info_montana.iloc[i]['Elevacion']

  folium.Marker(
      location=[float(Latitud), float(Longitud)],
      tooltip= Nombre,
      popup = f'Elevacion: {Elevacion} metros',
      icon = folium.Icon(color ='blue', icon='info-sign' )
      ). add_to(map)

  if Nombre == "CHIMBORAZO":
    folium.Circle(
        radius = 10_000,
        location = [float (Latitud), float (Longitud)],
        color='crimson',
        fill=True,
        fill_color='crimson').add_to(map)
map